
// UI
// export const SIDEBAR_TOGGLE = 'SIDEBAR_TOGGLE';
// export const SIDEBAR_OPEN = 'SIDEBAR_OPEN';
// export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE';
// export const SIDEBAR_OPENED = 'SIDEBAR_OPENED';
// export const SIDEBAR_CLOSED = 'SIDEBAR_CLOSED';


// FUNCTIONALITY
export const FIND_PARKINGS = 'FIND_PARKINGS';
export const FIND_PARKINGS_SUCCESS = 'FIND_PARKINGS_SUCCESS';
export const FIND_PARKINGS_ERR = 'FIND_PARKINGS_ERR';

export const FIND_CHARGERS = 'FIND_CHARGERS';
export const FIND_CHARGERS_SUCCESS = 'FIND_CHARGERS_SUCCESS';
export const FIND_CHARGERS_ERR = 'FIND_CHARGERS_ERR';

export const ADD_PARKING = 'ADD_PARKING';
export const ADD_PARKING_SUCCESS = 'ADD_PARKING_SUCCESS';
export const ADD_PARKING_ERR = 'ADD_PARKING_ERR';

export const ADD_CHARGER = 'ADD_CHARGER';
export const ADD_CHARGER_SUCCESS = 'ADD_CHARGER_SUCCESS';
export const ADD_CHARGER_ERR = 'ADD_CHARGER_ERR';
